import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { VideoProvider } from '@/context/VideoContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <VideoProvider>
          <main className="flex flex-col">
            <header className="flex items-center p-5 h-16 w-full border-b border-slate-600">
              <h1>Caio Play</h1>
            </header>
            <div className="grid grid-cols-[1fr_300px] p-5">
              {children}
              <aside>
                <ul>
                  <li>video 1</li>
                  <li>video 2</li>
                  <li>video 3</li>
                </ul>
              </aside>
            </div>
          </main>
        </VideoProvider>
      </body>
    </html>
  )
}
